dataset: 'CARS'
validation_size: 0.0
net: 'convnext_tiny_26'
batch_size: 48
batch_size_pretrain: 128
# epochs_net: 84
epochs: 84
optimizer: 'Adam'
# lr: 0.000225
lr: 0.05
# lr_block: 0.000225
lr_block: 0.0005
# lr_net: 0.000225
lr_net: 0.0005
# lr_classifier_fine_tune: 0.005
weight_decay: 0.0
disable_cuda: False
log_dir: ''
num_features: 0
image_size: 224
state_dict_dir_net: ''
# epochs_fine_tune: 24
freeze_epochs: 24
dir_for_saving_images: ''
disable_pretrained: False
epochs_pretrain: 12
weighted_loss: False
seed: 1
gpu_ids: '0'
num_workers: 8
bias: False
num_classes: 196
head_type: 'rbf_head'
detect_prob_flag: False
notebook: False
margin: 0.025
visualize_data: False
#------------------------- Hydra Config ------------------------#
hydra:
  job:
    name: ${net}_${head_type}_${dataset}_seed_${seed}
  run:
    dir: outputs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}
