dataset: 'PETS'
validation_size: 0.0
net: 'convnext_tiny_26'    # 'resnet50'
batch_size: 48
batch_size_pretrain: 128
epochs: 60
optimizer: 'Adam'
lr: 0.05
lr_block: 0.0001
lr_net: 0.0001
weight_decay: 0.0
disable_cuda: False
log_dir: './experiment_logs/pipnet_pets_cnext26'
num_features: 0
image_size: 224
state_dict_dir_net: ''
freeze_epochs: 10
dir_for_saving_images: 'visualization_results_summary'
disable_pretrained: False
epochs_pretrain: 10
weighted_loss: False
seed: 1
gpu_ids: '0'
num_workers: 8
bias: False
visualize_data: False
head_type: 'pipnet_head'
#------------------------- Hydra Config ------------------------#
hydra:
  job:
    name: ${net}_${head_type}_${dataset}_seed_${seed}
  run:
    dir: outputs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}
